inkcut/inkcut

- README.md
It's already in the repo title but nice to have it in the readme text itself as well
> Link to project homepage

- plugins/inkscape/inkcut.py
- plugins/inkscape/inkcut_cut.py
- plugins/inkscape/inkcut_open.py
First for review of the general approach. Of course the 2 duplicated methods
should be shared, can you recommend the idiomatic way to do that?
> When exporting from Inkscape, convert text nodes to paths

- plugins/inkscape/inkcut.py
- plugins/inkscape/inkcut_cut.py
- plugins/inkscape/inkcut_open.py
> Revert "Revert "When exporting from Inkscape, convert text nodes to paths""

- docs/installing.md
Proposed updates to the install documentation primarily based on issues encountered when installing on Ubuntu 16 and Ubuntu 17.04.
> Update re: missing enamlx error

- docs/device-setup.md
The 'Text-Only' driver had awful artifacts - probably it tried to do word
wrapping? The 'Raw Queue' driver works much better.
> Recommend 'Raw Queue' driver

- inkcut/device/view.enaml
It seemed best to just give some examples.
> Document 'output scale' option (#55)

- inkcut/core/svg.py
Handles the common case that the viewBox is at the origin.
Also translating is left as separate issue #69
> Scale based on the viewBox

- inkcut/device/pi/manifest.enaml
> Apply default config to pi device factory as well

- .travis.yml
- requirements.txt
Only an incremental improvement: still fails to actually run the tests
> Simplify travis config

- inkcut/device/drivers/manifest.enaml
Mistyped length parameter as height, causing Inkcut to crash on launch. Tested latest file to make sure everything was working. Sorry for the confusion!
> Fixed height --> length and tested

- plugins/inkscape/inkcut.py
To make it work even when a display is still in use
> Pass '-a' parameter to xvfb

- MANIFEST.in
> Also include res/*.svg through MANIFEST.in

- inkcut/core/svg.py
With the current implementation using the "Cut selection" extension doesn't work if the selected node is embedded in a group. 
This solves that by using xpath queries to find the selected node(s) and all of their parents, then passing the "allowed" nodes so they can check whether or not to include their child nodes.
To reference in the docs
> Cut selection

- inkcut/core/utils.py
- inkcut/job/models.py
- inkcut/job/ordering.py
For #26 
The "shortest path" could use some help.
> Add some basic path optimizations

- .gitignore
- inkcut/device/plugin.py
- inkcut/device/transports/raw/manifest.enaml
- inkcut/device/transports/raw/plugin.py
- inkcut/device/transports/raw/settings.enaml
- inkcut/device/transports/serialport/plugin.py
- inkcut/monitor/manifest.enaml
- inkcut/monitor/plugin.py
- inkcut/monitor/view.enaml
- inkcut/res/icons/.directory
- inkcut/ui/dock.enaml
- inkcut/ui/plugin.py
Abstracted out some code to a RawFDDevice, still needs some work (hopefully to support the LPR ports)
The monitor still needs a little work, but it's nice if you want to view the serial connection..
For #132
> WIP: Add device monitor

- docs/developer.md
I needed to install these additional dependencies to be able to run inkcut.
> Add dependencies to developer instructions

- .travis.yml
- inkcut/app.py
- inkcut/core/plugin.py
- tests/data/arc-path.svg
- tests/data/arc-rotated-path.svg
- tests/data/rect.svg
- tests/test_app.py
- tests/test_svg.py
> Write faulthandler crashes to crash.txt in log folder

- docs/installing.md
> Add python3-pyqt5.qtsvg dependency to install docs

- inkcut/device/plugin.py
- inkcut/device/view.enaml
- inkcut/job/ordering.py
The current method is too confusing.
> Refactor ouput orientation

- inkcut/device/filters/blade_offset.py
- inkcut/device/plugin.py
- inkcut/job/models.py
Adds proper handling of curves and corners.
> New blade offset algorithm

- inkcut/core/manifest.enaml
- inkcut/core/utils.py
- inkcut/device/dialogs.enaml
- inkcut/device/filters/manifest.enaml
- inkcut/device/filters/view.enaml
- inkcut/device/manifest.enaml
- inkcut/device/pi/view.enaml
- inkcut/device/protocols/view.enaml
- inkcut/device/transports/disk/settings.enaml
- inkcut/device/transports/raw/settings.enaml
- inkcut/device/transports/serialport/settings.enaml
- inkcut/device/view.enaml
- inkcut/job/dialogs.enaml
- inkcut/job/manifest.enaml
- inkcut/job/settings.enaml
- inkcut/job/view.enaml
- inkcut/joystick/view.enaml
- inkcut/monitor/view.enaml
- inkcut/preview/manifest.enaml
- inkcut/preview/settings.enaml
- inkcut/preview/view.enaml
- inkcut/ui/manifest.enaml
- inkcut/ui/settings.enaml
Replace all tr occurences and add a few missing translations
> Use QApplication.translate instead of tr(), so lupdate can see the strings

- inkcut/job/view.enaml
Mirror feature was reversed, X-axis mirroring means that Y-axis should be multiplied by -1.
> Fix inverted mirroring about x/y axis

- inkcut/device/plugin.py
> fix #193 init transport on startup

- plugins/inkscape/inkcut.py
- plugins/inkscape/inkcut_cut.py
- plugins/inkscape/inkcut_open.py
Fix Inkscape 1.0 compatibility, for the record changes are explained here : https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0
Tested with 1.0 beta 2
> Inkscape 1.0 compatibility

- docs/supported-devices.md
- inkcut/device/drivers/manifest.enaml
Adding device manifest for Silhouette Cameo 4.
Also updated the docs for this device. I see "Silhouette Cameo" is already listed but it's not clear what version of the Cameo those refer to, so I left them in.
> Add Silhouette Cameo 4 device

- inkcut/core/svg.py
- tests/data/arc-cut.svg
Fixes #262
Makes sure to use elliptical equations rather than circle equations
> Fix sweep length for non-90deg arcs

- plugins/inkscape/inkcut_cut.py
- plugins/inkscape/inkcut_open.py
> Fix 259 : import submodule directly

- inkcut/device/drivers/manifest.enaml
- inkcut/device/plugin.py
- inkcut/device/transports/qtserialport/manifest.enaml
- inkcut/device/transports/qtserialport/plugin.py
- inkcut/device/transports/qtserialport/settings.enaml
+ New QtSerialPort connection (inkcut.device.transports packages)
+ New UI for editing the configuration
+ New DeviceDriver configuration for Sekonic SPL-450 plotter
Works well on Win10!
> QtSerialPort connection

- inkcut/device/transports/printer/plugin.py
At least show something on the console when invoking lpr fails.
> Rudimentary LPR error handling

- docs/installing.md
This describes how to add $USER to dialout, so that the software works without error after setup.
> describe how to give permissions for dialout

- .github/workflows/ci.yml
Get the tests running again #347
For now somewhat minimalistic version. So that at least something get's run. Can be later expanded with the combination of configs that maintainers think are important to test.
> Initial version for GHA testing.
