inkcut/inkcut

inkcut/core/svg.py, inkcut/device/drivers/manifest.enaml
Only non-rotated arcs for now.
cx and cy seem accurate, but the arc and sweep appear to have a pretty
large (rounding?) errors - do you see where these might be coming from?
=> Preliminary arc support

inkcut/device/drivers/manifest.enaml, inkcut/device/extensions.py, inkcut/device/plugin.py
Can this be done in a more generic way? something like this
for key in default_config.keys():
device.config[key] = default_config[key]
Didn't work right away since 'config' is not a Dict... should it be?
=> Allow configuring the scale from the driver manifest (#56)

inkcut/device/drivers/manifest.enaml
The Silhouette Portrait has strange orientation/axes. Probably makes most
sense to show it in landscape orientation, keeping the origin at the
bottom-left of the inkcut screen.
=> Show Silhouette Portrait in Landscape (#59)

inkcut/core/svg.py
By making parseUnit more forgiving, to for example successfully load the attached svg.
[tb.svg.txt](https://github.com/codelv/inkcut/files/1896544/tb.svg.txt)
=> Support files with viewBox without width or height

inkcut/device/drivers/manifest.enaml
Tested with Vision VE-810XD engraver using serial (19200 rate, hardware handshaking, X-axis mirroring, return to origin). Added to manifest.enaml.
=> Add Vision VE-810XD engraver to manifest.enaml

setup.py
Do the filtering in the dependency filters instead of as a conditional
when evaluating setup.py, so you can create a package with python2 and
then install it under python3. For #78
=> Add all deps to install_requires

.travis.yml, docs/developer.md, docs/installing.md, setup.py
Moved 'installing from source' to developer page
Uploaded to pypi-test, *seems* OK now, try it with:
pip3 install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple inkcut-rabooftest4
Perhaps another final test before publishing 2.0.4 to the real pypi?
=> Document releasing, installing

inkcut/device/transports/printer/plugin.py
Changes to prevent a crash.
with win 10 and 8.1
win32print.EnumPrinters add paramete win32print.EnumPrinters
win32print.WritePrinter convert string to bytearray
=> repair win32print

inkcut/device/dialogs.enaml, inkcut/device/plugin.py, inkcut/device/transports/parallelport/manifest.enaml, inkcut/device/transports/parallelport/plugin.py, inkcut/device/transports/parallelport/settings.enaml
For #25 and #117 . Works on linux. Collects info on usb/printers using `udevadm` . 
The user must be added to the `lp` group via `sudo usermod -a -G lp your-username`
Would be nice to be able get info for non-usb parallel ports.
Also thoughts on dropping cups stuff altogether (or making it an optional install)?
=> Add direct parallel port connection type

docs/supported-devices.md
Inkcut can (also) communicate with the pii-60 plotter via the parallel port.
=> supported-devices.md: Add parallel port for pii-60

inkcut/device/transports/serialport/plugin.py
A hack to workaround for https://github.com/pyserial/pyserial/issues/286 since pyserial they seem to not want to do any more releases. 
Should fix https://github.com/inkcut/inkcut/issues/163, https://github.com/inkcut/inkcut/issues/171,
=> Add hack to patch pyserial error

plugins/inkscape/inkcut.py
Multiple --verb's are no longer supported. With actions, by default the GUI
isn't shown, so xvfb is no longer necessary.
=> Update inkscape preprocessing to inkscape 1.0

inkcut/monitor/view.enaml
To test, create a drawing with some text. Create like 20-30 copies and send it via serial port. After several copies the UI starts to lag as reported at https://inkcut.org/t/inkcut-glitchy-slow-after-cutting-cycle-breaches-est-15-minutes/66/
This fixes that.
=> Fix UI lag on large cuts due to monitor text insertion being slow

plugins/inkscape/inkcut4inkscape.py, plugins/inkscape/inkcut_cut.inx, plugins/inkscape/inkcut_cut.py, plugins/inkscape/inkcut_open.inx, plugins/inkscape/inkcut_open.py
Ohterwise, with an unfortunate PYTONPATH, inkcut would no longer
start since it'd try to use inkcut.py from the extension
instead of the application itself...
=> Avoid name clash between inkscape plugin and inkcut itself

plugins/inkscape/inkcut_cut.inx, plugins/inkscape/inkcut_open.inx
Don't specify inkex.py as a dependency: this is not needed, and
from inkscape 1.2 onwards this file does not exist anymore
(https://gitlab.com/inkscape/extensions/-/merge_requests/460)
Fixes #339
=> inkscape extension: no inkex.py dependency

plugins/inkscape/inkcut4inkscape.py
It is deprecated, and not used anyway AFAICS
fixes #342
=> avoid distutils

inkcut/device/protocols/gcode.py, inkcut/device/protocols/manifest.enaml, inkcut/device/protocols/view.enaml
**Description**
Exact set of G-code commands varies between different devices, controller/firmware manufacturers.  There are also a lot of DIY devices potentially requiring very specific startup sequences or creative approaches for activating the tool.
Add protocol configuration for following properties
* decimal precision (#301)
* configurable tool lifting code (Implicit, Custom, Z)
* disabling builtin startup sequence
I tried to write the new code so that in default configuration, everything works just like it did before.
Tool lifting choice works like this:
* Implict -> assumes that device automatically lifts the tool for G00 moves and lowers it for G01
* Custom -> user can define custom G-code to execute when tool needs to be activated or deactivated. Useful for DIY devices using …
=> Make gcode protocol more configurable.

inkcut/device/view.enaml, inkcut/job/dialogs.enaml, inkcut/job/models.py
Use the units from "Settings/Settings/Job" in job approval window and Live view.
Previously approval window always used inches, but live view used numerical value of inches  with unit suffix from settings.
Closes #319
=> Use selected units in job aproval and live view.

inkcut/core/utils.py, inkcut/device/filters/blade_offset.py
Logic bug in how `split_painter_path` handles last curve caused it to not be included. This was observable when using plotting order modes other than normal or reversed.
Blade offset had same bug, but wasn't able to trigger it because at that stage of processing last curve was always followed by linear movement, even when input only contains one or two curves. Probably some kind of connection move. Still fixed it since it didn't seem like good idea to rely on it.
Before:
After:
Test file:
[drawing4.zip](https://github.com/inkcut/inkcut/files/9792144/drawing4.zip)
=> Fix handling of last curve.

inkcut/device/dialogs.enaml, inkcut/device/drivers/manifest.enaml, inkcut/device/extensions.py, inkcut/device/pi/manifest.enaml, inkcut/device/plugin.py
* add UI for choosing driver before device is created
* disable driver switching after device is created
* add command for copying a device
In theory the driver switching after device is created can't work for general case where the specific driver 'DeviceDriver(Declarative)' has custom factory which creates some `Device(Model)` subclass like it is for PiDevice. In practice it doesn't properly work even in the simple cases as indicated by #282 .  Switching driver after device has been created also introduces problem of how to deal with user modified fields which conflict with values from driver manifest, or cases where you are switching between devices with different set of supported protocols.
Copying functionality is useful if you want to create multiple slightly different configs for …
=> Rework device creation to use all the data from driver.

inkcut/core/models.py, inkcut/device/plugin.py
Prevented unintended sharing of device area property when copying a device.
Closes #360
=> Fix device area cloning.

inkcut/core/declarative.py
Seems like jsonpickle 2.2.0 doesn't properly handle  Atom Event fields. Enaml Declarative has some which got serialized thus later breaking loading process of settings.
See #361 for more details on my attempts debugging what goes wrong there and scenarios for triggering the problem.
@frmdstryr  Do you remember what parts of enaml Declarative you tried to exclude from removal with `(not metadata or                                        not metadata.get('d_final', False))` code?
Closes #361
=> Don't serialize events from in enaml Declarative.

inkcut/device/protocols/hpgl.py, inkcut/device/protocols/manifest.enaml, inkcut/device/protocols/view.enaml
Intended for use with USB-connected plotters that need a little padding between commands.
Tested on US Cutter MH365 MK2.
fixes #367
=> Add optional newline terminator for HPGL.

inkcut/monitor/view.enaml
* Add UI for enabling "add newline" functionality.  The functionality was already there, but from what I could tell there was no way to enable it. 
* Fix scroll to end . I assume it got accidentally removed in https://github.com/inkcut/inkcut/commit/218571f3e4ba8c015d02011bb1c6f3c3287096b5 . In case the scrolling was one of the reasons for slowdown, it's always possible to disable it.
* remove \r from output from output field. This was causing response from device not to show up properly.
=> Restore broken monitor functionality.

.github/workflows/ci.yml
* replace unsupported python version 3.7 with current latest 3.12
* change how package is installed because direct calling of setup.py is deprecated
* switch QT backend for running it on Linux in headless mode
There are two macOS because on github actions macos-13 is a  mac with x86_64 cpu, but macos-latest is using ARM cpu.
=> Fix CI tests.

inkcut/ui/plugin.py
`pkg_resource` is deprecated and is removed in Pyhton 3.12.
Note: This would raise the required Python version to Python 3.8. If compatibility with earlier Python versions is required, we could use the `importlib_metadata` backport package (see [here](https://setuptools.pypa.io/en/latest/pkg_resources.html)). Python 2 compatibility would be broken never the less, but  Python 2 is EOL since 2020 and all support for this legacy version could be removed.
=> Replace pkg_resources with importlib.metadata

inkcut/device/dialogs.enaml, inkcut/device/plugin.py
The prefix `_default_` is reserved for methods generating the default value for an attribute (in atom). If we are using the method `_default_protocol` without a member `protocol`, a MissingMemberWarning will be generated:
```
atom/meta/atom_meta.py:555: MissingMemberWarning: _default_ method _default_protocol on class 'Device' does not match any member defined on the Atom object.
```
=> Don't use prefix `_default_` if no member exists
